### PR TITLE
Remove 81, add some planes found in OGN DDB

### PR DESCRIPTION
**Pull request by roeles**

### CODE REVIEW

**Comment by roeles** [comment]
*prik*

**Comment by GliderGeek** [comment]
Nice, looks good. Was a bit confused by the readme only stating to commit 2
files. Can you update that? (Am on mobile now). Also i will give you merge
rights to prevent delays like this 😊

**Comment by roeles** [comment]
Yeah, I can change that. 
Merge rights would be lovely <3

**Comment by GliderGeek** [comment]
Nice, let’s also add glidertracker. In the meantime i invited you as collaborator, does this give you merge rights?

**Comment by roeles** [comment]
I am allowed to merge now.

**Pull request merged**
